/* Generated by `swift package fuzz-init`. You should never need to edit this.
 *
 * The fuzz executable is deliberately pure C. SwiftPM's native build system
 * renames a *Swift* executable target's `main` to `<Module>_main` and aliases
 * `main` to it, which collides with the `main` libFuzzer's runtime provides. A
 * C target has no Swift `main` to rename, so the collision never arises and
 * this builds under both build systems.
 *
 * Both symbols below come from the fuzz target's Swift library, via the file
 * swift-fuzz's FuzzTargetPlugin generates.
 */
#include <inttypes.h>
#include <stddef.h>

int swift_fuzz_run(const uint8_t *data, size_t size);
void swift_fuzz_initialize(void);

int LLVMFuzzerInitialize(int *argc, char ***argv) {
  (void)argc;
  (void)argv;
  swift_fuzz_initialize();
  return 0;
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  return swift_fuzz_run(data, size);
}
