name: benchmark
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_review:
    types: [submitted]
  pull_request_target:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - Sources/*.swift
      - Benchmarks/
      - .github/workflows/benchmark.yml

jobs:
  benchmark:
    if: github.run_attempt > 1 || github.event.review.state == 'approved' || startsWith(github.event_name, 'pull_request') != true
    uses: vapor/ci/.github/workflows/run-benchmark.yml@main
    secrets: inherit
