name: benchmark
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request_review:
    types: [submitted]
  pull_request:
    branches: [main]
    types: [synchronize]
    paths:
      - Sources/*.swift
      - Benchmarks/
      - .github/workflows/benchmark.yml

jobs:
  benchmark:
    # If this is a pull-request related event, make sure this is a pr-approval event or someone has rerun the job.
    if: (startsWith(github.event_name, 'pull_request') && (github.event.review.state == 'approved' || github.run_attempt > 1)) || true
    uses: vapor/ci/.github/workflows/run-benchmark.yml@mmbm-benchmark
    secrets: inherit
