name: benchmark
on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
  pull_request:
    branches: [main]
    types: [synchronize]
    paths:
      - Sources/*.swift
      - Benchmarks/
      - .github/workflows/benchmark.yml

jobs:
  benchmark-vs-thresholds:
    # Run the job only if it's a manual workflow dispatch, or if this event is a pull-request approval event, or if someone has rerun the job.
    if: github.event_name == 'workflow_dispatch' || github.event.review.state == 'approved' || github.run_attempt > 1
    uses: vapor/ci/.github/workflows/run-benchmark.yml@mmbm-benchmark
    secrets: inherit
