name: test
on:
  pull_request: { branches: ['*'] }
  push: { branches: ['main'] }

jobs:
  unit-tests:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    with:
      with_linting: true
    secrets: inherit
