name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { branches: ['*'] }
  push: { branches: ['main'] }

jobs:
  unit-tests:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@main
    secrets: inherit
